### ISSUE TITLE
getCurrentConnections does not work on mac

### ISSUE THREAD

**Issue by felixgalindo** [friedrith/node-wifi#28]

**Comment by peterbe** [comment]
I too get nothing:
```javascript
wifi.init({
    iface : null // network interface, choose a random wifi interface if set to null
});

wifi.getCurrentConnections(function(err, currentConnections) {
  if (err) {
    console.error(err);
    throw err
    // console.log(err)
  }
  console.log('CURRENT CONNETIONS');
  console.log(currentConnections)
})
```
Using the latest version.

**Comment by peterbe** [comment]
To anybody else ending up here and being too eager to wait for a fix, here's what I did:
https://github.com/peterbe/howsmywifi/blob/2c479bcbd344fce0b9a77b9fe972a38e24b78262/index.js#L30-L68

I only have a mac so I wouldn't even be able to test `node-wifi` on non-macs. The `spawn()` solution works for mac. I was going to use that as a fallback.

**Comment by xdadda** [comment]
As mentioned no need for a fix, just call the Promise as explained above. 
And it will work on all platforms.

**Comment by peterbe** [comment]
Sweet! Thanks. [Removed my hack](https://github.com/peterbe/howsmywifi/commit/c0451eb0984e959e9c43885b88096a7f13bc51db)

**Comment by friedrith** [comment]
Sorry for the late. I have pushed a new version that corrects the bug of callback on macOS.
