### ISSUE TITLE
Does not work with NM 1.10.X

### ISSUE THREAD

**Issue by aaronovz1** [friedrith/node-wifi#36]
NetworkManager 1.10.X now uses a pager for most of the nmcli output. This breaks parsing. See https://bugzilla.gnome.org/show_bug.cgi?id=791808

I think if each nmcli command is prefixed with PAGER= as mentioned in the bug comments, this should get around the problem.

**Comment by friedrith** [comment]
Ok could be useful to set environment variable PAGER to "". Do you find it correct ?

**Comment by aaronovz1** [comment]
According to the latest comments on that bug ticket it seems there shouldn't be an issue because node-wifi is using the --terse option which should disable pager. I think this might be a non issue and can be closed.
