### ISSUE TITLE
License irritation.

### ISSUE THREAD

**Issue by ClausBendig** [friedrith/node-wifi#37]
Hi, 

I'm confused, in the [npmjs package](https://www.npmjs.com/package/node-wifi) this library is licensed as LGPL-3.0, but in this repository it is GPL-3.0.

Which license is it? Hopefully LGPL-3.0.

Could you please clarify it.

**Comment by friedrith** [comment]
I think it was planned to be a GPL 3.0. I'm gonna check and come back as soon as I have the answer. But I might change it if it is really a problem.

**Comment by ClausBendig** [comment]
Thx, for setting it to the LGPL-3.0.
